Update for Tailwind ver 1
JeffreyWay/laravel-mix-tailwind pull request #8
Opened 2019-03-21 23:17 UTC by rverrips

Hi Jeffery
Not sure if this is the best approach (certainly the simplest) by just updating to run with Tailwind-ver 1.   Could potentially do a fs.stat and see which of the config files is there, or simply version the npm  accordingly to match tailwind version numbers?
Either way, let me know if you'd like me to help with this in any other ways.
Appreciate all you do!
Roy

2019-03-22 14:21 UTC, johannebert commented
Hey,

you can just paste a right config filename into function like this:

```js
mix.tailwind('./tailwind.config.js');
```

Regards

2019-03-22 18:58 UTC, rverrips commented
Thanks @johannebert - That is what I've been doing, but would suggest it's better to have the defaults set as per the currently supported upstream which will soon be v1 which is why I suggested to version the npm according which is why I included the peer dependency sample.   

Either way, just trying to help where I can ...

2019-05-19 11:07 UTC, mvdnbrk commented on package.json
> -    "laravel-mix": "^2.1.7"
This can be updated to ^4.0.15.

2019-05-19 11:10 UTC, mvdnbrk requested changes
Dependency `laravel-mix` can be updated to ^4.0.15.

2019-05-25 16:45 UTC, mvdnbrk commented
I have published an [updated package](https://laravel-mix.com/extensions/tailwindcss) which is compatible with TailwindCSS v1.0 and higher.

As of version 1.0 the `tailwind.config.js` is optional, so if there isn't a config file in the root of your project it uses the default Tailwind config.

If you are you using a version below 1.0 it will detect the `tailwind.js` config file and it will use that one.

2020-03-17 22:06 UTC, closed without merging